---
- name: Docker | Check if docker is installed
  stat:
    path: /usr/bin/docker
  register: docker_bin

# - name: Docker | Add docker-engine repo and install docker (China specific)
#   # shell: "curl -fsSL https://get.docker.com/ | bash -s - {% if docker_china_mirror %}--mirror AzureChinaCloud{% endif %}"
#   # Cheat the setup ...
#   shell: |
#     curl -fsSL https://get.docker.com/ | \
#     sed -e 's/gpgcheck=1/gpgcheck=0/' \
#         -e 's/https:\/\/yum.dockerproject.org/http:\/\/mirrors.aliyun.com\/docker-engine\/yum/' | \
#     bash -s -
#   when: not docker_bin.stat.exists and docker_china_mirror

# - name: Docker | Add docker-engine repo and install docker (Global)
#   shell: |
#     curl -fsSL https://get.docker.com/ | \
#     bash -s -
#   when: not docker_bin.stat.exists and not docker_china_mirror

- name: Docker | Install packages dependencies
  when: ansible_os_family == 'RedHat'
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Docker | Add yum repository
  get_url:
    url: "https://download.docker.com/linux/centos/docker-ce.repo"
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644
  when: ansible_distribution != 'Amazon' and ansible_os_family == 'RedHat'

- name: Docker | Install docker-ce dependencies
  yum:
    name: "docker-ce"
    state: present
  when: ansible_distribution != 'Amazon' and ansible_os_family == 'RedHat'

- name: Docker | Install docker on Amazon Linux
  command: amazon-linux-extras install docker -y
  when: ansible_distribution == 'Amazon'

# we prefer newer version of docker
# see https://wiki.debian.org/AptConfiguration
- name: Docker | set apt package pin preference
  when: ansible_os_family == 'Debian'
  template:
    src: apt_preference_docker.j2
    dest: /etc/apt/preferences.d/docker
    owner: root
    group: root
    mode: 0644

- name: "Docker | Install docker on debian"
  when: ansible_os_family == 'Debian'
  package:
    name: "docker.io"
    state: present

- name: Create /etc/docker directory
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root

- name: Change docker0 ip
  template:
    src: docker-daemon.json.j2
    dest: /etc/docker/daemon.json
  when: docker0_ip is defined

- name: Docker | Start and Enable docker
  service:
    name: docker
    state: started
    enabled: true

# - include: configure.yml
- include: packages.yml
- include: users.yml
