---

- name: Docker | RedHat | Install epel-release
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution != "Amazon"

- name: Docker | RedHat | Install python-pip
  yum:
    name: python-pip
    state: present
  when: ansible_os_family == "RedHat"

# debian before 11 has python2.7
- name: Docker | Debian | Install python-pip for debian <= 10
  when: ansible_os_family == "Debian" and ansible_distribution_major_version|int < 11
  apt:
    name: python-pip
    state: present

# starting from debian 11, there is only python3
- name: Docker | Debian | Install python-pip for debian >= 11
  when: ansible_os_family == "Debian" and ansible_distribution_major_version|int >= 11
  apt:
    name: python3-pip
    state: present

- name: Docker | Install Pip extensions
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    extra_args: "{% if docker_pip_mirror_enable %} -i {{ docker_pip_mirror }} {% endif %}"
  with_items: "{{ docker_pip_packages }}"
