---
# Add users allowed to manage docker
- name: Docker | Add the Users to the docker group
  user:
    name: "{{ item }}"
    createhome: False
    groups: docker
    append: True
  with_items: "{{ docker_users }}"
